const tarot = {
  _cards: {
    name: [
      "The Fool",
      "Magician",
      "High Priestess",
      "Empress",
      "Emperor",
      "Hierophant",
      "Lovers",
      "Chariot",
      "Strength",
      "Hermit",
      "Wheel of Fortune",
      "Justice",
      "Hanged Man",
      "Death",
      "Temperance",
      "Devil",
      "Tower",
      "Star",
      "Moon",
      "Sun",
      "Judgment",
      "World",
    ],
    description: [
      "Beginnings",
      "Power, Action",
      "Mystery, Intuition",
      "Femininity, Beauty",
      "Structure, Solidity",
      "Trandition, Belief",
      "Love, Union",
      "Control, Willpower",
      "Strength, Courage",
      "Introspection",
      "Karma, Destiny",
      "Truth, Justice",
      "Sacrifice",
      "Transition",
      "Balance, Purpose",
      "Bondage, Addiction",
      "Disaster, Upheaval",
      "Hope, Renewal",
      "Illusion, Fear",
      "Warmth, Vitality",
      "Absolution",
      "Completion, Travel",
    ],
  },
};
